policy:
  approval:
    - name: Parent Workflow with Matrix Jobs succeeded
      requires:
        conditions:
          has_workflow_result:
            conclusions:
              - success
            workflows:
              - .github/workflows/parent.yml