name: Dependent Workflow

on:
  workflow_run:
    workflows: ["Parent Workflow"]
    types:
      - completed

jobs:
  dependent-job:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run dependent workflow task
        run: |
          echo "Running dependent workflow task..."
          echo "Parent workflow SHA: ${{ github.event.workflow_run.head_sha }}"
          echo "Parent workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
          sleep 3
          echo "Dependent workflow completed successfully"