name: Parent Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  call-reusable-workflow:
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: false
    uses: ./.github/workflows/matrix-jobs.yml
    with:
      environment: staging